default: cpsc2150/extendedTicTacToe/GameScreen.java cpsc2150/extendedTicTacToe/GameBoard.java cpsc2150/extendedTicTacToe/BoardPosition.java
	javac cpsc2150/extendedTicTacToe/GameScreen.java cpsc2150/extendedTicTacToe/GameBoard.java cpsc2150/extendedTicTacToe/BoardPosition.java

run: cpsc2150/extendedTicTacToe/GameScreen.class cpsc2150/extendedTicTacToe/GameBoard.class cpsc2150/extendedTicTacToe/BoardPosition.class
	java cpsc2150.extendedTicTacToe.GameScreen

clean:
	rm cpsc2150/extendedTicTacToe/GameScreen.class cpsc2150/extendedTicTacToe/GameBoard.class cpsc2150/extendedTicTacToe/BoardPosition.class
